prd:
  catalog_name: mlops_prd_
  schema_name: model_test

acc:
  catalog_name: mlops_acc_
  schema_name: model_test

dev:
  catalog_name: mlops_prod
  schema_name: model_test


# MLflow Experiments
experiment_name_basic: /Shared/sklearn-basic
experiment_name_custom: /Shared/sklearn-custom


# LightGBM or sklearn model parameters
parameters:
  learning_rate: 0.05
  n_estimators: 200
  max_depth: 6


# sklearn breast cancer dataset (ALL numeric)
num_features:
  - mean radius
  - mean texture
  - mean perimeter
  - mean area
  - mean smoothness
  - mean compactness
  - mean concavity
  - mean concave points
  - mean symmetry
  - mean fractal dimension
  - radius error
  - texture error
  - perimeter error
  - area error
  - smoothness error
  - compactness error
  - concavity error
  - concave points error
  - symmetry error
  - fractal dimension error
  - worst radius
  - worst texture
  - worst perimeter
  - worst area
  - worst smoothness
  - worst compactness
  - worst concavity
  - worst concave points
  - worst symmetry
  - worst fractal dimension

cat_features: []   # No categorical columns in sklearn dataset

target: target      # sklearn target column
